---
title: "Análisis de la carrera - Luis Carlos Lozano Caballero"
output:
  flexdashboard::flex_dashboard:
    theme:
      bg: "#FFFFFF"
      fg: "#101010" 
      primary: "#FFF8DC"
      base_font:
        google: Prompt
      code_font:
        google: JetBrains Mono
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(paqueteMET)
library(ggplot2)
library(dplyr)


# Install thematic and un-comment for themed static plots (i.e., ggplot2)
# thematic::thematic_rmd()
```

Column {data-width=200}
-----------------------------------------------------------------------

### Participantes de acuerdo a su categoría

```{r}
ggplot(data = CarreraLuz22, aes(x = categoria)) + 
  geom_bar(colour="#BA8111", fill="#FF6347") + 
  xlab("Categoria") + ylab("Cantidad")+ 
  theme(panel.background = element_rect(fill = "#FFF8DC"))

```
Column {data-width=200}


### Distribución tiempo en minutos de las mujeres

```{r}
ggplot(CarreraLuz22[CarreraLuz22$sex == "Mujer",], aes(x=timerun/60)) +
  geom_histogram(binwidth=5, color="black", fill="#FFC0CB") +
  labs(x="Tiempo de carrera", y="Frecuencia", color="Hombres") +
  theme_classic()+
  theme(panel.background = element_rect(fill = "#FFF8DC"))
```

Column {data-width=200}
-----------------------------------------------------------------------

### Porcentaje de participantes de acuerdo al género

```{r}
#Convertimos a porcentaje
porcentaje <- CarreraLuz22 %>% 
                group_by(sex) %>% 
                count() %>% 
                ungroup() %>% 
                mutate(percentage=`n`/sum(`n`) * 100)
#Grafico circular
ggplot(porcentaje, aes(x=1, y=percentage, fill=sex)) +
        geom_bar(stat="identity") +
        geom_text(aes(label = paste0(round(percentage,1),"%")), 
                  position = position_stack(vjust = 0.5)) +
        coord_polar(theta = "y") + 
        theme_void()+
  scale_fill_manual(values=c("#AFEEEE", "#FFC0CB"))+
  theme(panel.background = element_rect(fill = "#FFF8DC"))+
  theme(plot.title = element_text(hjust=0.5))
```



### Distribución tiempo en minutos de los hombres

```{r}
ggplot(CarreraLuz22[CarreraLuz22$sex == "Hombre",], aes(x=timerun/60)) +
  geom_histogram(binwidth=5, color="black", fill="#AFEEEE") +
  labs(x="Tiempo de carrera", y="Frecuencia", color="Hombres") +
  theme_classic()+
  theme(panel.background = element_rect(fill = "#FFF8DC"))
```




Column {data-width=200}
-----------------------------------------------------------------------

### Relación categoría - tiempo de carrera

```{r}
ggplot(data = CarreraLuz22, aes(x = categoria, y = timerun )) +
  geom_point(color = "#FF6347") +
  labs(x="categoria", y="timerun")+
  theme(panel.background = element_rect(fill = "#FFF8DC"))
```

### Tiempo de carrera de acuerdo al género

```{r}
ggplot(data= CarreraLuz22, aes(x=sex, y=timerun))+
  geom_jitter(size=1, alpha=0.7, color="#FF6347")+
  geom_boxplot(alpha=0.7)+
  xlab("Genero")+
  ylab("Tiempo de carrera")+
  theme(panel.background = element_rect(fill = "#FFF8DC"))
```

Column {data-width=150}
-----------------------------------------------------------------------
### Ciudad con mayor cantidad de participantes
```{r}
frecuencia <- table(CarreraLuz22$origen)
valor_mas_frecuente <- names(which.max(frecuencia))
cat(valor_mas_frecuente)


```

### Participante con mayor edad
```{r}
cat(max(CarreraLuz22$edad))
```
### Promedio de tiempo en minutos de todos los participantes
```{r}
cat(mean(CarreraLuz22$timerun)/60)
```
### Cantidad de participantes de la carrera
```{r}
cat(nrow(CarreraLuz22))
```

### Menor cantidad de tiempo en minutos
```{r}
cat(min(CarreraLuz22$timerun/60))
```